### Trae todos los productos en la base de datos
GET http://localhost:8080/api/productos
# Content-Type: application/json
# authorization: Bearer 

### busca producto por id
GET http://localhost:8080/api/productos/6452dc83c6cb9eb064973976

### agrega un producto 
POST http://localhost:8080/api/productos
Content-Type: application/json

{
    "title": "Remera Puma Essentials Heather",
    "description": "Material: Algodón",
    "price": "6.099",
    "thumbnails": "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw31f6dfb9/products/PU_845895-06/PU_845895-06-1.JPG",
    "code": "N2R86",
    "stock": "30"
}

### actualiza un producto
PUT http://localhost:8080/api/productos/64530670c7bfad2d935779fc
Content-Type: application/json

{
    "description": "Modelo: 2023",
    "price": 35.999,
    "stock": 15
}

### elimina un producto
DELETE http://localhost:8080/api/productos/64530670c7bfad2d935779fc