### register
POST http://localhost:8080/api/session/register
Content-Type: application/json

{
    "firtsName": "pablo",
    "lastName": "maguirre",
    "email": "maguirrepablo@hotmail.com",
    "userName": "macpablo",
    "birthDate": "1996-08-15",
    "password": "macpabli"
}
### login
post http://localhost:8080/api/session/login
Content-Type: application/json

{
    "email": "AguiarAndresok@outlook.es",
    "password": "andres"
}

### login
post http://localhost:8080/api/session/login
Content-Type: application/json

{
    "email": "adminCoder@coder.com",
    "password": "adminCod3r123"
}

### acceder al current
GET http://localhost:8080/api/session/current

### privada
GET http://localhost:8080/api/session/privada

### logout
GET http://localhost:8080/api/session/logout

