POST http://localhost:8080/api/session/register
Content-Type: application/json

{
    "firtsName": "pablo",
    "lastName": "canseco",
    "email": "canpablo@hotmail.com",
    "userName": "canpablo",
    "password": "canpabli"
}

###
POST http://localhost:8080/api/session/register
Content-Type: application/json

{
    "firtsName": "pablo",
    "lastName": "maguirre",
    "email": "maguirrepablo@hotmail.com",
    "userName": "macpablo",
    "password": "macpabli"
}