### Trae todos los usuarios
GET http://localhost:8080/api/users

### Busca un usuario por id
GET http://localhost:8080/api/users/2

### register
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "firtsName": "pablo",
    "lastName": "maguirre",
    "email": "maguirrepablo@hotmail.comm",
    "userName": "macpabloo",
    "birthDate": "1996-08-15",
    "password": "macpabli"
}

### register
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "firtsName": "peter",
    "lastName": "aguirre",
    "email": "aguirrePeter@gmail.com",
    "userName": "peterAG",
    "birthDate": "1996-08-15",
    "password": "peter"
}

### modifica un usuario
PUT http://localhost:8080/api/users/64a76dc733352244508586f9
Content-Type: application/json

{
    "userName": "PeterOG"
}

### modifica un usuario
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
    "firtsName": "pedro ezequiel",
    "email": "peterSanchez@gmail.com"
}

### Borra un usuarios
DELETE http://localhost:8080/api/users/64a892c287609a604619b495

### Borra un usuarios
DELETE http://localhost:8080/api/users/2